#!/usr/bin/env python3
"""Enter the P1 pilot corpus into data/processed/*.csv.

Idempotent: rewrites the rows it owns (all rows, since the tables start empty).
Run from the repository root.
"""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[0]
import sys
ROOT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.cwd()
P = ROOT / "data" / "processed"

CREATED_BY = "cc"
CREATED_DATE = "2026-08-26"
LLM_MODEL = "claude-fable-5"
PROMPT_V = "manual_transcription"

# ---------------------------------------------------------------- authors
# (author_id, display_name, author_type, orcid_or_viaf, notes)
AUTHORS = [
    ("auth_nedludd", "\"Ned Ludd\" / Army of Redressers", "labor_organization", "", "Pseudonymous collective signature used by Luddite framework-breakers"),
    ("auth_byron", "George Gordon Byron, Lord Byron", "politician", "", "Speaking in the House of Lords; poet by profession"),
    ("auth_ricardo", "David Ricardo", "academic", "", "Political economist; also an MP from 1819"),
    ("auth_ure", "Andrew Ure", "academic", "", "Chemist and factory-system advocate"),
    ("auth_wright", "Carroll D. Wright", "government_agency", "", "US Commissioner of Labor 1885-1905"),
    ("auth_wells", "David A. Wells", "academic", "", "Economist; former US Special Commissioner of the Revenue"),
    ("auth_gompers", "Samuel Gompers", "labor_organization", "", "President, American Federation of Labor"),
    ("auth_keynes", "John Maynard Keynes", "academic", "", ""),
    ("auth_compton", "Karl T. Compton", "academic", "", "President of MIT 1930-1948"),
    ("auth_wiener", "Norbert Wiener", "academic", "", "Founder of cybernetics"),
    ("auth_reuther", "Walter Reuther", "labor_organization", "", "President, United Automobile Workers; CIO"),
    ("auth_simon", "Herbert A. Simon", "academic", "", "Nobel laureate in economics 1978"),
    ("auth_leontief", "Wassily Leontief", "academic", "", "Nobel laureate in economics 1973"),
    ("auth_rifkin", "Jeremy Rifkin", "futurist", "", "Economic and social theorist, Foundation on Economic Trends"),
    ("auth_frey", "Carl Benedikt Frey", "academic", "", "Oxford Martin School"),
    ("auth_osborne", "Michael A. Osborne", "academic", "", "Department of Engineering Science, University of Oxford"),
    ("auth_deloitte", "Deloitte LLP", "consultancy", "", "UK practice"),
    ("auth_autor", "David H. Autor", "academic", "", "MIT Department of Economics"),
    ("auth_arntz", "Melanie Arntz", "academic", "", "ZEW Mannheim; lead author of OECD WP 189"),
    ("auth_oecd", "Organisation for Economic Co-operation and Development", "igo", "", "Publisher of the Social, Employment and Migration Working Paper series"),
    ("auth_hinton", "Geoffrey Hinton", "academic", "", "University of Toronto; Nobel laureate in physics 2024"),
    ("auth_pwc", "PricewaterhouseCoopers", "consultancy", "", "PwC UK Economic Outlook team"),
    ("auth_atkinson", "Robert D. Atkinson", "think_tank_private", "", "President, Information Technology and Innovation Foundation"),
    ("auth_goldman", "Goldman Sachs Global Investment Research", "financial_institution", "", "Briggs and Kodnani, Global Economics Analyst"),
    ("auth_amodei", "Dario Amodei", "industry_executive", "", "CEO, Anthropic"),
]

# ---------------------------------------------------------------- sources
# source_id, title, container_title, pub_date, source_type, venue_country,
# language_original, is_translation, url, archive_url, doi, retrieval_track, notes
SOURCES = [
    ("src_ludd1812", "Letter to Mr Smith, Shearing Frame Holder at Hill End, Yorkshire", "The Writings of the Luddites (Binfield, ed., 2004)", "1812-03-09", "pamphlet", "GB", "en", "false",
     "http://ludditebicentenary.blogspot.com/2012/03/9th-march-1812-letter-from-ned-ludd.html", "", "", "pilot_seed",
     "Pseudonymous threatening letter; text as transcribed in Binfield (2004) and the Luddite Bicentenary project"),
    ("src_byron1812", "Speech on the Frame Work Bill, House of Lords, 27 February 1812", "Hansard, HL Deb vol 21 cc964-79", "1812-02-27", "testimony", "GB", "en", "false",
     "https://historyofinformation.com/detail.php?id=4654", "", "", "pilot_seed",
     "Byron's maiden speech in the Lords, opposing capital punishment for frame-breaking"),
    ("src_ricardo1821", "On Machinery (chapter 31)", "On the Principles of Political Economy and Taxation, 3rd edition", "1821", "book", "GB", "en", "false",
     "https://www.marxists.org/reference/subject/economics/ricardo/tax/ch31.htm", "", "", "pilot_seed",
     "Chapter added in the third edition, reversing Ricardo's earlier position"),
    ("src_ure1835", "The Philosophy of Manufactures", "", "1835", "book", "GB", "en", "false",
     "https://wikieducator.org/images/c/c9/Modern_History_Sourcebook_URE.pdf", "", "", "pilot_seed",
     "Defence of the factory system; the canonical early reassurance text"),
    ("src_wright1886", "First Annual Report of the Commissioner of Labor: Industrial Depressions", "", "1886", "government_report", "US", "en", "false",
     "", "https://catalog.hathitrust.org/Record/008595729", "", "pilot_seed",
     "First report of the newly created US Bureau of Labor"),
    ("src_wells1889", "Recent Economic Changes", "", "1889", "book", "US", "en", "false",
     "https://en.wikisource.org/wiki/Popular_Science_Monthly/Volume_35/September_1889/Recent_Economic_Changes", "", "", "pilot_seed",
     "Serialised in Popular Science Monthly before book publication"),
    ("src_gompers1894", "Letter on Labor in Industrial Society, to Judge Peter Grosscup", "", "1894-09", "pamphlet", "US", "en", "false",
     "https://www.let.rug.nl/usa/documents/1876-1900/samuel-gompers-letter-on-labor-in-industrial-society-to-judge-peter-grosscup-september-1894.php", "", "", "pilot_seed",
     "Open letter written in the aftermath of the Pullman strike"),
    ("src_keynes1930", "Economic Possibilities for our Grandchildren", "The Nation and Athenaeum", "1930-10", "magazine_article", "GB", "en", "false",
     "https://www.marxists.org/reference/subject/economics/keynes/1930/our-grandchildren.htm", "", "", "pilot_seed",
     "Published in two parts, 11 and 18 October 1930; later collected in Essays in Persuasion (1931)"),
    ("src_compton1938", "The Bogey of Technological Unemployment", "Technology Review", "1938-12", "magazine_article", "US", "en", "false",
     "https://www.technologyreview.com/2024/01/27/1087041/technological-unemployment-elon-musk-jobs-ai/", "", "", "pilot_seed",
     "Quoted at length in the magazine's own 2024 retrospective; original December 1938 issue to be consulted for the verbatim check"),
    ("src_wiener1949", "Letter to Walter Reuther, 13 August 1949", "", "1949-08-13", "pamphlet", "US", "en", "false",
     "https://libcom.org/history/father-cybernetics-norbert-wieners-letter-uaw-president-walter-reuther", "", "", "pilot_seed",
     "Private letter offering Wiener's automatic-machinery work to the UAW; the argument is restated in The Human Use of Human Beings (1950)"),
    ("src_reuther1955", "Testimony before the Subcommittee on Economic Stabilization, Joint Committee on the Economic Report: Automation and Technological Change", "", "1955-10", "testimony", "US", "en", "false",
     "https://www.jec.senate.gov/reports/84th%20Congress/Automation%20and%20Technological%20Change%20-%20Hearings%20(75).pdf", "", "", "pilot_seed",
     "The hearings that put 'automation' on the US policy agenda"),
    ("src_simon1960", "The New Science of Management Decision", "", "1960", "book", "US", "en", "false",
     "", "", "", "pilot_seed",
     "Harper & Brothers, 1960; reprinted 1965, which is the source of the widespread misdating of the quotation to 1965"),
    ("src_leontief1983", "Technological Advance, Economic Growth, and the Distribution of Income", "Population and Development Review 9(3)", "1983-09", "journal_article", "US", "en", "false",
     "", "https://www.jstor.org/stable/1973315", "10.2307/1973315", "pilot_seed",
     "Based on Leontief's address to the National Academy of Engineering symposium, 30 June 1983"),
    ("src_rifkin1995", "The End of Work: The Decline of the Global Labor Force and the Dawn of the Post-Market Era", "", "1995", "book", "US", "en", "false",
     "http://pinguet.free.fr/rifkin1995.pdf", "", "", "pilot_seed",
     "G. P. Putnam's Sons, 1995"),
    ("src_freyosborne2013", "The Future of Employment: How Susceptible Are Jobs to Computerisation?", "Oxford Martin School Working Paper", "2013-09-17", "working_paper", "GB", "en", "false",
     "https://oms-www.files.svdcdn.com/production/downloads/academic/The_Future_of_Employment.pdf", "", "", "pilot_seed",
     "Later published in Technological Forecasting and Social Change 114 (January 2017): 254-280"),
    ("src_deloitte2014", "London Futures - Agiletown: The Relentless March of Technology and London's Response", "Deloitte London Futures", "2014-11-10", "consultancy_report", "GB", "en", "false",
     "https://www.robots.ox.ac.uk/~mosb/public/pdf/299/uk-london-futures-agiletown-nov-14.pdf", "", "", "pilot_seed",
     "Deloitte's live URL is a redirect loop; the Oxford-hosted copy is byte-identical (SHA-256 c552c3a2b114d87ba4805d77397cae7423c68db5d03a02fff99988d1e74e4ff0) to the Wayback capture of Deloitte's original PDF. Frey and Osborne are credited as the named researchers; the method crosswalks their 702 US O*NET-SOC probabilities onto 369 UK SOC 2010 codes rather than re-estimating"),
    ("src_autor2015", "Why Are There Still So Many Jobs? The History and Future of Workplace Automation", "Journal of Economic Perspectives 29(3)", "2015-08", "journal_article", "US", "en", "false",
     "https://www.aeaweb.org/articles?id=10.1257%2Fjep.29.3.3", "", "10.1257/jep.29.3.3", "pilot_seed",
     ""),
    ("src_arntz2016", "The Risk of Automation for Jobs in OECD Countries: A Comparative Analysis", "OECD Social, Employment and Migration Working Papers No. 189", "2016-05-14", "igo_report", "FR", "en", "false",
     "https://www.oecd.org/en/publications/the-risk-of-automation-for-jobs-in-oecd-countries_5jlz9h56dvq7-en.html", "", "10.1787/5jlz9h56dvq7-en", "pilot_seed",
     "Task-based rebuttal to the occupation-based Frey-Osborne estimate"),
    ("src_hinton2016", "Remarks at the Machine Learning and the Market for Intelligence conference, Toronto", "", "2016-10", "speech_transcript", "CA", "en", "false",
     "https://www.youtube.com/watch?v=2HMPRXstSvQ", "", "", "pilot_seed",
     "Conference video; the radiology remark is widely quoted from this session"),
    ("src_pwc2017", "Will Robots Steal Our Jobs? The Potential Impact of Automation on the UK and Other Major Economies", "UK Economic Outlook, March 2017", "2017-03", "consultancy_report", "GB", "en", "false",
     "https://www.pwc.co.uk/economic-services/assets/international-impact-of-automation-feb-2018.pdf", "", "", "pilot_seed",
     "Figures later revised in the February 2018 international update"),
    ("src_itif2022", "Oops, the Predicted 47 Percent of Job Loss From AI Didn't Happen", "ITIF Blog", "2022-09-30", "think_tank_report", "US", "en", "false",
     "https://itif.org/publications/2022/09/30/oops-the-predicted-47-percent-of-job-loss-from-ai-didnt-happen/", "", "", "pilot_seed",
     "Retrospective reassurance: argues the 47 percent era's forecasts did not materialise"),
    ("src_goldman2023", "The Potentially Large Effects of Artificial Intelligence on Economic Growth", "Goldman Sachs Global Economics Analyst", "2023-03-26", "consultancy_report", "US", "en", "false",
     "https://www.goldmansachs.com/insights/articles/generative-ai-could-raise-global-gdp-by-7-percent", "", "", "pilot_seed",
     "Authors Joseph Briggs and Devesh Kodnani; source_type consultancy_report pending a decision on a financial-institution value (DR-002)"),
    ("src_amodei2025", "Behind the Curtain: A White-Collar Bloodbath", "Axios", "2025-05-28", "newspaper_article", "US", "en", "false",
     "https://www.axios.com/2025/05/28/ai-jobs-white-collar-unemployment-anthropic", "", "", "pilot_seed",
     "Reported speech: Amodei's claims as quoted by Axios; primary transcript not located"),
]

# ---------------------------------------------------------------- predictions
# Only fields that vary are listed; the rest are filled from DEFAULTS.
PRED_FIELDS = [
    "prediction_id", "source_id", "quote_verbatim", "quote_locator", "prediction_date",
    "claim_summary", "claim_type", "level", "geography", "geography_text",
    "occupation_code", "occupation_system", "industry_code", "industry_system",
    "direction", "magnitude_type", "estimate_type", "magnitude_value", "magnitude_low",
    "magnitude_high", "magnitude_headline", "magnitude_unit", "specificity_tier",
    "horizon_stated_text", "horizon_type", "horizon_start_year", "horizon_end_year",
    "horizon_operationalized", "mechanism_specified", "mechanism_text", "mechanism_type",
    "is_conditional", "panic_valence", "is_secondary_report", "primary_source_status",
    "derived_from_prediction_id", "extraction_method", "llm_model", "llm_prompt_version",
    "created_by", "created_date", "verified_by", "verified_date", "record_status",
]

PREDICTIONS = [
    dict(
        prediction_id="pred_ludd1812", source_id="src_ludd1812",
        quote_verbatim="Information has just been given in that you are a holder of those detestable Shearing Frames, and I was desired by my Men to write to you and give you fair Warning to pull them down",
        quote_locator="Letter, opening paragraph",
        prediction_date="1812-03-09",
        claim_summary="Shearing frames held by a Yorkshire cloth finisher are denounced as machinery that must be destroyed because it displaces skilled croppers.",
        claim_type="employment_outcome", level="occupation",
        geography="GB", geography_text="Huddersfield district, Yorkshire",
        occupation_code="", occupation_system="hisco",
        direction="displacement", magnitude_type="qualitative_partial", estimate_type="none",
        specificity_tier="T4_rhetorical",
        horizon_stated_text="", horizon_type="none",
        mechanism_specified="false", panic_valence="alarm",
        primary_source_status="secondary_only",
        tech=[("shearing_frame", True)],
        authors=[("auth_nedludd", "institutional", "labor_organization")],
    ),
    dict(
        prediction_id="pred_byron1812", source_id="src_byron1812",
        quote_verbatim="the adoption of certain machinery in the stocking frame, by which one man performed the work of many, and the superfluous labourers were thrown out of employment",
        quote_locator="HL Deb 27 February 1812, vol 21 c966",
        prediction_date="1812-02-27",
        claim_summary="Improved stocking frames let one worker do the work of many, throwing the surplus workers out of employment in the Nottinghamshire hosiery trade.",
        claim_type="employment_outcome", level="occupation",
        geography="GB", geography_text="Nottinghamshire",
        direction="displacement", magnitude_type="qualitative_partial", estimate_type="none",
        specificity_tier="T3_directional",
        horizon_stated_text="", horizon_type="none",
        mechanism_specified="true",
        mechanism_text="one man performed the work of many",
        mechanism_type="cost_substitution",
        panic_valence="alarm", primary_source_status="primary_located",
        tech=[("labour_saving_machinery", True)],
        authors=[("auth_byron", "sole", "politician")],
    ),
    dict(
        prediction_id="pred_ricardo1821", source_id="src_ricardo1821",
        quote_verbatim="the opinion entertained by the labouring class, that the employment of machinery is frequently detrimental to their interests, is not founded on prejudice and error, but is conformable to the correct principles of political economy",
        quote_locator="Principles, 3rd ed., ch. 31 'On Machinery'",
        prediction_date="1821",
        claim_summary="The substitution of machinery for labour can reduce the gross produce that funds employment, so displacement of workers is consistent with correct political economy rather than a workers' error.",
        claim_type="employment_outcome", level="country_region",
        geography="GB", geography_text="England",
        direction="net_negative", magnitude_type="qualitative_partial", estimate_type="none",
        specificity_tier="T3_directional",
        horizon_stated_text="", horizon_type="none",
        mechanism_specified="true",
        mechanism_text="conversion of circulating capital, which funds the wage bill, into fixed capital",
        mechanism_type="cost_substitution",
        panic_valence="neutral_forecast", primary_source_status="primary_located",
        tech=[("labour_saving_machinery", True)],
        authors=[("auth_ricardo", "sole", "academic")],
    ),
    dict(
        prediction_id="pred_ure1835", source_id="src_ure1835",
        quote_verbatim="the constant aim and effect of scientific improvement in manufactures are philanthropic, as they tend to relieve the workmen either from niceties of adjustment which exert the eyesight and muscles, or from painful repetition of effort which distort or wear out the frame",
        quote_locator="The Philosophy of Manufactures, Book I, ch. 1",
        prediction_date="1835",
        claim_summary="Mechanical improvement in manufactures relieves workers of arduous tasks rather than displacing them, offering lighter continuous labour at steady wages.",
        claim_type="employment_outcome", level="industry",
        geography="GB", geography_text="British manufacturing districts",
        direction="transformation_neutral", magnitude_type="qualitative_partial", estimate_type="none",
        specificity_tier="T3_directional",
        horizon_stated_text="", horizon_type="none",
        mechanism_specified="true",
        mechanism_text="machinery takes over the physically arduous and precision-demanding elements of the task",
        mechanism_type="capability_parity",
        panic_valence="reassurance", primary_source_status="primary_located",
        tech=[("mechanization_general", True)],
        authors=[("auth_ure", "sole", "academic")],
    ),
    dict(
        prediction_id="pred_wright1886", source_id="src_wright1886",
        quote_verbatim="the introduction of machinery has caused only a temporary displacement of labor, and that in the end more persons are employed than before",
        quote_locator="First Annual Report of the Commissioner of Labor (1886), section on machinery and labor",
        prediction_date="1886",
        claim_summary="The US Commissioner of Labor concludes that machinery displaces labour only temporarily and that employment ultimately rises above its previous level.",
        claim_type="employment_outcome", level="country_region",
        geography="US", geography_text="United States",
        direction="net_positive", magnitude_type="qualitative_partial", estimate_type="none",
        specificity_tier="T3_directional",
        horizon_stated_text="in the end", horizon_type="vague_phrase",
        mechanism_specified="true",
        mechanism_text="cheapened production expands demand and re-absorbs displaced workers",
        mechanism_type="demand_shift",
        panic_valence="reassurance", primary_source_status="secondary_only",
        tech=[("mechanization_general", True)],
        authors=[("auth_wright", "institutional", "government_agency")],
    ),
    dict(
        prediction_id="pred_wells1889", source_id="src_wells1889",
        quote_verbatim="the displacement of labor by machinery has been greater during the last quarter of a century than ever before, and the tendency to over-production may become chronic",
        quote_locator="Recent Economic Changes, ch. 'Economic Disturbance since 1873'",
        prediction_date="1889",
        claim_summary="Machinery is displacing workers faster than they are re-absorbed, and the resulting over-production may become a chronic rather than a cyclical condition.",
        claim_type="employment_outcome", level="country_region",
        geography="US", geography_text="United States and Western Europe",
        direction="net_negative", magnitude_type="qualitative_partial", estimate_type="none",
        specificity_tier="T2_semi_quantified",
        horizon_stated_text="may become chronic", horizon_type="vague_phrase",
        mechanism_specified="true",
        mechanism_text="productive capacity grows faster than the market can absorb output",
        mechanism_type="scale_speed",
        panic_valence="alarm", primary_source_status="secondary_only",
        tech=[("mechanization_general", True)],
        authors=[("auth_wells", "sole", "academic")],
    ),
    dict(
        prediction_id="pred_gompers1894", source_id="src_gompers1894",
        quote_verbatim="the introduction of machinery is turning into idleness thousands, faster than new industries are founded, and yet you ask, workingmen to be satisfied",
        quote_locator="Letter to Judge Peter Grosscup, September 1894",
        prediction_date="1894-09",
        claim_summary="Machinery is idling workers faster than new industries can absorb them, so displacement is outpacing job creation.",
        claim_type="employment_outcome", level="country_region",
        geography="US", geography_text="United States",
        direction="net_negative", magnitude_type="qualitative_partial", estimate_type="none",
        specificity_tier="T3_directional",
        horizon_stated_text="", horizon_type="none",
        mechanism_specified="true",
        mechanism_text="rate of displacement exceeds the rate at which new industries are founded",
        mechanism_type="scale_speed",
        panic_valence="alarm", primary_source_status="primary_located",
        tech=[("mechanization_general", True)],
        authors=[("auth_gompers", "sole", "labor_organization")],
    ),
    dict(
        prediction_id="pred_keynes1930", source_id="src_keynes1930",
        quote_verbatim="We are being afflicted with a new disease of which some readers may not yet have heard the name, but of which they will hear a great deal in the years to come - namely, technological unemployment. This means unemployment due to our discovery of means of economising the use of labour outrunning the pace at which we can find new uses for labour. But this is only a temporary phase of maladjustment.",
        quote_locator="Economic Possibilities for our Grandchildren, section II",
        prediction_date="1930-10",
        claim_summary="Labour-saving discovery is outrunning the discovery of new uses for labour, producing technological unemployment, which Keynes expects to be a temporary phase of maladjustment rather than a permanent condition.",
        claim_type="employment_outcome", level="global",
        geography="", geography_text="progressive countries",
        direction="net_negative", magnitude_type="qualitative_partial", estimate_type="none",
        specificity_tier="T2_semi_quantified",
        horizon_stated_text="in the years to come; a temporary phase of maladjustment",
        horizon_type="vague_phrase",
        mechanism_specified="true",
        mechanism_text="means of economising the use of labour outrunning the pace at which we can find new uses for labour",
        mechanism_type="scale_speed",
        panic_valence="neutral_forecast", primary_source_status="primary_located",
        tech=[("mechanization_general", True)],
        authors=[("auth_keynes", "sole", "academic")],
    ),
    dict(
        prediction_id="pred_compton1938", source_id="src_compton1938",
        quote_verbatim="technological unemployment is a bogey; in the long run technological progress creates more jobs than it destroys",
        quote_locator="Technology Review, December 1938 (as quoted in MIT Technology Review, 27 January 2024)",
        prediction_date="1938-12",
        claim_summary="Technological progress creates more employment than it destroys over the long run, so technological unemployment is a false alarm.",
        claim_type="employment_outcome", level="country_region",
        geography="US", geography_text="United States",
        direction="net_positive", magnitude_type="qualitative_partial", estimate_type="none",
        specificity_tier="T3_directional",
        horizon_stated_text="in the long run", horizon_type="vague_phrase",
        mechanism_specified="true",
        mechanism_text="new industries founded on new technologies absorb more workers than the displaced trades shed",
        mechanism_type="demand_shift",
        panic_valence="reassurance", primary_source_status="secondary_only",
        tech=[("mechanization_general", True)],
        authors=[("auth_compton", "sole", "academic")],
    ),
    dict(
        prediction_id="pred_wiener1949", source_id="src_wiener1949",
        quote_verbatim="This apparatus is extremely flexible, and susceptible to mass production, and will undoubtedly lead to the factory without employees; as for example, the automatic automobile assembly line. In the hands of the present industrial set-up, the unemployment produced by such plants can only be disastrous.",
        quote_locator="Letter to Walter Reuther, 13 August 1949",
        prediction_date="1949-08-13",
        claim_summary="Programmable automatic machinery will produce factories without employees, and under existing industrial arrangements the resulting unemployment would be disastrous.",
        claim_type="employment_outcome", level="industry",
        geography="US", geography_text="United States manufacturing",
        direction="displacement", magnitude_type="qualitative_total", estimate_type="none",
        specificity_tier="T3_directional",
        horizon_stated_text="", horizon_type="none",
        mechanism_specified="true",
        mechanism_text="flexible, mass-producible automatic control apparatus replaces the human operator on the assembly line",
        mechanism_type="capability_parity",
        is_conditional="true",
        panic_valence="alarm", primary_source_status="primary_located",
        tech=[("automation_general", True), ("computing", False)],
        authors=[("auth_wiener", "sole", "academic")],
    ),
    dict(
        prediction_id="pred_reuther1955", source_id="src_reuther1955",
        quote_verbatim="Automation is a new and more advanced stage of technological progress, and unless we manage it wisely it can bring mass unemployment and economic chaos rather than the abundance it makes possible",
        quote_locator="Testimony, Automation and Technological Change hearings, October 1955",
        prediction_date="1955-10",
        claim_summary="Automation can deliver either abundance or mass unemployment depending on whether its introduction is deliberately managed; unmanaged, it threatens large-scale displacement.",
        claim_type="employment_outcome", level="country_region",
        geography="US", geography_text="United States",
        direction="displacement", magnitude_type="qualitative_partial", estimate_type="none",
        specificity_tier="T3_directional",
        horizon_stated_text="", horizon_type="conditional",
        mechanism_specified="true",
        mechanism_text="the pace of automation outruns the economy's capacity to create replacement employment",
        mechanism_type="scale_speed",
        is_conditional="true",
        panic_valence="alarm", primary_source_status="secondary_only",
        tech=[("automation_general", True)],
        authors=[("auth_reuther", "institutional", "labor_organization")],
    ),
    dict(
        prediction_id="pred_simon1960", source_id="src_simon1960",
        quote_verbatim="Technologically, as I have argued earlier, machines will be capable, within twenty years, of doing any work that a man can do.",
        quote_locator="The New Science of Management Decision (1960), p. 38",
        prediction_date="1960",
        claim_summary="Within twenty years machines will be capable of performing any work a human can perform.",
        claim_type="capability_milestone", level="global",
        geography="", geography_text="",
        direction="displacement", magnitude_type="qualitative_total", estimate_type="point",
        specificity_tier="T1_quantified",
        horizon_stated_text="within twenty years", horizon_type="explicit_duration",
        horizon_start_year="1960", horizon_end_year="1980", horizon_operationalized="false",
        mechanism_specified="false",
        panic_valence="neutral_forecast", primary_source_status="secondary_only",
        tech=[("computing", True), ("artificial_intelligence", False)],
        authors=[("auth_simon", "sole", "academic")],
    ),
    dict(
        prediction_id="pred_leontief1983", source_id="src_leontief1983",
        quote_verbatim="the role of humans as the most important factor of production is bound to diminish in the same way that the role of horses in agricultural production was first diminished and then eliminated by the introduction of tractors",
        quote_locator="Population and Development Review 9(3), p. 403",
        prediction_date="1983-09",
        claim_summary="Humans' role as the most important factor of production will diminish as computers and automation spread, on the pattern by which tractors first reduced and then eliminated the horse.",
        claim_type="employment_outcome", level="global",
        geography="", geography_text="industrial economies",
        direction="net_negative", magnitude_type="qualitative_partial", estimate_type="none",
        specificity_tier="T3_directional",
        horizon_stated_text="", horizon_type="none",
        mechanism_specified="true",
        mechanism_text="successive waves of more capable machines substitute for human labour as they once substituted for animal power",
        mechanism_type="capability_parity",
        panic_valence="alarm", primary_source_status="primary_located",
        tech=[("computing", True), ("automation_general", False)],
        authors=[("auth_leontief", "sole", "academic")],
    ),
    dict(
        prediction_id="pred_rifkin1995", source_id="src_rifkin1995",
        quote_verbatim="We are entering a new phase in world history - one in which fewer and fewer workers will be needed to produce the goods and services for the global population",
        quote_locator="The End of Work, Introduction",
        prediction_date="1995",
        claim_summary="Ever fewer workers will be required to produce the world's goods and services, moving the global economy toward a near-workerless condition.",
        claim_type="employment_outcome", level="global",
        geography="", geography_text="world economy",
        direction="net_negative", magnitude_type="qualitative_partial", estimate_type="none",
        specificity_tier="T2_semi_quantified",
        horizon_stated_text="in the years ahead; the early decades of the twenty-first century",
        horizon_type="vague_phrase",
        mechanism_specified="true",
        mechanism_text="information technology and automation raise output per worker faster than demand for labour grows",
        mechanism_type="scale_speed",
        panic_valence="alarm", primary_source_status="primary_located",
        tech=[("computing", True), ("automation_general", False)],
        authors=[("auth_rifkin", "sole", "futurist")],
    ),
    dict(
        prediction_id="pred_freyosborne2013", source_id="src_freyosborne2013",
        quote_verbatim="According to our estimate, 47 percent of total US employment is in the high risk category, meaning that associated occupations are potentially automatable over some unspecified number of years, perhaps a decade or two.",
        quote_locator="The Future of Employment (2013), p. 38",
        prediction_date="2013-09-17",
        claim_summary="47 percent of total US employment falls in a high-risk category of occupations that are potentially automatable over perhaps a decade or two.",
        claim_type="exposure_risk", level="country_region",
        geography="US", geography_text="United States",
        occupation_system="soc2018",
        direction="displacement", magnitude_type="percent_of_jobs", estimate_type="point",
        magnitude_value="47", magnitude_headline="47", magnitude_unit="percent of US employment",
        specificity_tier="T2_semi_quantified",
        horizon_stated_text="over some unspecified number of years, perhaps a decade or two",
        horizon_type="vague_phrase",
        mechanism_specified="true",
        mechanism_text="occupations whose tasks face no near-term engineering bottleneck in perception and manipulation, creative intelligence, or social intelligence become automatable",
        mechanism_type="capability_parity",
        panic_valence="alarm", primary_source_status="primary_located",
        tech=[("machine_learning", True), ("artificial_intelligence", False)],
        authors=[("auth_frey", "lead", "academic"), ("auth_osborne", "coauthor", "academic")],
    ),
    dict(
        prediction_id="pred_deloitte2014", source_id="src_deloitte2014",
        quote_verbatim="They estimate that on average, 35 per cent of current jobs in the UK are at high risk over the next ten to twenty years. The figure for London is 30 per cent.",
        quote_locator="Agiletown (2014), p. 8",
        prediction_date="2014-11-10",
        claim_summary="35 percent of current UK jobs, and 30 percent of London jobs, are at high risk of automation over the next ten to twenty years, applying the Frey-Osborne methodology to UK occupational data.",
        claim_type="exposure_risk", level="country_region",
        geography="GB", geography_text="United Kingdom",
        direction="displacement", magnitude_type="percent_of_jobs", estimate_type="point",
        magnitude_value="35", magnitude_headline="35", magnitude_unit="percent of UK jobs",
        specificity_tier="T1_quantified",
        horizon_stated_text="over the next ten to twenty years", horizon_type="explicit_duration",
        horizon_start_year="2014", horizon_end_year="2034", horizon_operationalized="false",
        mechanism_specified="true",
        mechanism_text="applies the Frey-Osborne occupational computerisation probabilities to UK occupational employment",
        mechanism_type="capability_parity",
        panic_valence="alarm", primary_source_status="secondary_only",
        derived_from_prediction_id="pred_freyosborne2013",
        tech=[("machine_learning", True), ("computing", False)],
        authors=[("auth_deloitte", "institutional", "consultancy")],
    ),
    dict(
        prediction_id="pred_autor2015", source_id="src_autor2015",
        quote_verbatim="journalists and even expert commentators tend to overstate the extent of machine substitution for human labor and ignore the strong complementarities between automation and labor that increase productivity, raise earnings, and augment demand for labor",
        quote_locator="Journal of Economic Perspectives 29(3), p. 5",
        prediction_date="2015-08",
        claim_summary="Commentary overstates machine substitution for labour and ignores complementarities that raise productivity and increase labour demand.",
        claim_type="employment_outcome", level="country_region",
        geography="US", geography_text="United States",
        direction="transformation_neutral", magnitude_type="qualitative_partial", estimate_type="none",
        specificity_tier="T3_directional",
        horizon_stated_text="", horizon_type="none",
        mechanism_specified="true",
        mechanism_text="automation complements the tasks it does not replace, raising productivity and the demand for labour in those tasks",
        mechanism_type="demand_shift",
        panic_valence="reassurance", primary_source_status="primary_located",
        tech=[("computing", True), ("automation_general", False)],
        authors=[("auth_autor", "sole", "academic")],
    ),
    dict(
        prediction_id="pred_arntz2016", source_id="src_arntz2016",
        quote_verbatim="we find that, on average across the 21 OECD countries, 9 % of jobs are automatable",
        quote_locator="OECD Social, Employment and Migration Working Paper No. 189, p. 4",
        prediction_date="2016-05-14",
        claim_summary="A task-based analysis finds that on average 9 percent of jobs across 21 OECD countries are automatable, well below occupation-based estimates.",
        claim_type="exposure_risk", level="country_region",
        geography="", geography_text="21 OECD countries",
        direction="displacement", magnitude_type="percent_of_jobs", estimate_type="point",
        magnitude_value="9", magnitude_headline="9", magnitude_unit="percent of jobs",
        specificity_tier="T1_quantified",
        horizon_stated_text="over the next decades", horizon_type="vague_phrase",
        mechanism_specified="true",
        mechanism_text="automatability assessed on the task composition of individual jobs rather than on occupational averages",
        mechanism_type="capability_parity",
        panic_valence="reassurance", primary_source_status="primary_located",
        tech=[("machine_learning", True), ("automation_general", False)],
        authors=[("auth_arntz", "lead", "academic"), ("auth_oecd", "institutional", "igo")],
    ),
    dict(
        prediction_id="pred_hinton2016", source_id="src_hinton2016",
        quote_verbatim="It's just completely obvious that within five years deep learning is going to do better than radiologists. It might be 10 years, but we've got plenty of radiologists already.",
        quote_locator="Machine Learning and the Market for Intelligence conference, Toronto, October 2016",
        prediction_date="2016-10",
        claim_summary="Deep learning will outperform radiologists within five years, so training of new radiologists should stop now.",
        claim_type="employment_outcome", level="occupation",
        geography="", geography_text="",
        occupation_code="29-1224", occupation_system="soc2018",
        direction="displacement", magnitude_type="qualitative_total", estimate_type="point",
        specificity_tier="T1_quantified",
        horizon_stated_text="within five years", horizon_type="explicit_duration",
        horizon_start_year="2016", horizon_end_year="2021", horizon_operationalized="false",
        mechanism_specified="true",
        mechanism_text="deep learning surpasses human performance on the image-interpretation task that defines the occupation",
        mechanism_type="capability_parity",
        panic_valence="alarm", primary_source_status="secondary_only",
        tech=[("machine_learning", True), ("artificial_intelligence", False)],
        authors=[("auth_hinton", "sole", "academic")],
    ),
    dict(
        prediction_id="pred_pwc2017", source_id="src_pwc2017",
        quote_verbatim="up to 30% of UK jobs could potentially be at high risk of automation by the early 2030s, lower than the US (38%) or Germany (35%), but higher than Japan (21%)",
        quote_locator="UK Economic Outlook, March 2017, section 4 summary",
        prediction_date="2017-03",
        claim_summary="Up to 30 percent of UK jobs, 38 percent of US jobs, 35 percent of German jobs and 21 percent of Japanese jobs could be at high risk of automation by the early 2030s.",
        claim_type="exposure_risk", level="country_region",
        geography="GB", geography_text="United Kingdom, United States, Germany, Japan",
        direction="displacement", magnitude_type="percent_of_jobs", estimate_type="point",
        magnitude_value="30", magnitude_headline="38", magnitude_unit="percent of jobs at high risk",
        specificity_tier="T1_quantified",
        horizon_stated_text="by the early 2030s", horizon_type="explicit_year",
        horizon_start_year="2017", horizon_end_year="2032", horizon_operationalized="true",
        mechanism_specified="true",
        mechanism_text="extends the Frey-Osborne approach with task-level data from the OECD PIAAC survey",
        mechanism_type="capability_parity",
        panic_valence="alarm", primary_source_status="primary_located",
        derived_from_prediction_id="pred_freyosborne2013",
        tech=[("machine_learning", True), ("automation_general", False)],
        authors=[("auth_pwc", "institutional", "consultancy")],
    ),
    dict(
        prediction_id="pred_itif2022", source_id="src_itif2022",
        quote_verbatim="the doomsayers were wrong. Not only has the U.S. economy not seen massive job losses from automation, it has seen historically low rates of occupational churn",
        quote_locator="ITIF blog post, 30 September 2022",
        prediction_date="2022-09-30",
        claim_summary="The predicted mass job losses from automation did not occur; US occupational churn over the period was historically low.",
        claim_type="employment_outcome", level="country_region",
        geography="US", geography_text="United States",
        direction="transformation_neutral", magnitude_type="qualitative_partial", estimate_type="none",
        specificity_tier="T2_semi_quantified",
        horizon_stated_text="", horizon_type="none",
        mechanism_specified="true",
        mechanism_text="measured occupational churn rates have fallen rather than risen over the period of the automation forecasts",
        mechanism_type="other",
        panic_valence="reassurance", primary_source_status="primary_located",
        tech=[("artificial_intelligence", True), ("automation_general", False)],
        authors=[("auth_atkinson", "sole", "think_tank_private")],
    ),
    dict(
        prediction_id="pred_goldman2023", source_id="src_goldman2023",
        quote_verbatim="if generative AI delivers on its promised capabilities, the labor market could face significant disruption... we estimate that roughly two-thirds of current jobs are exposed to some degree of AI automation, and that generative AI could substitute for up to one-fourth of current work. Extrapolating our estimates globally suggests that generative AI could expose the equivalent of 300mn full-time jobs to automation.",
        quote_locator="Global Economics Analyst, 26 March 2023, pp. 1-2",
        prediction_date="2023-03-26",
        claim_summary="Generative AI could expose the equivalent of 300 million full-time jobs globally to automation, with roughly two-thirds of current jobs exposed to some degree and up to one-quarter of current work substitutable.",
        claim_type="exposure_risk", level="global",
        geography="", geography_text="global",
        direction="displacement", magnitude_type="absolute_jobs", estimate_type="point",
        magnitude_value="300000000", magnitude_headline="300000000",
        magnitude_unit="full-time equivalent jobs exposed",
        specificity_tier="T1_quantified",
        horizon_stated_text="over a 10 year period", horizon_type="explicit_duration",
        horizon_start_year="2023", horizon_end_year="2033", horizon_operationalized="false",
        mechanism_specified="true",
        mechanism_text="generative AI substitutes for a share of the task content of exposed occupations",
        mechanism_type="capability_parity",
        is_conditional="true",
        panic_valence="alarm", primary_source_status="secondary_only",
        tech=[("generative_ai", True), ("artificial_intelligence", False)],
        authors=[("auth_goldman", "institutional", "financial_institution")],
    ),
    dict(
        prediction_id="pred_amodei2025", source_id="src_amodei2025",
        quote_verbatim="AI could wipe out half of all entry-level white-collar jobs - and spike unemployment to 10-20% in the next one to five years",
        quote_locator="Axios, 28 May 2025, opening paragraph (reported speech)",
        prediction_date="2025-05-28",
        claim_summary="AI could eliminate half of entry-level white-collar jobs and raise unemployment to 10-20 percent within one to five years.",
        claim_type="employment_outcome", level="country_region",
        geography="US", geography_text="United States",
        direction="displacement", magnitude_type="percent_of_jobs", estimate_type="range",
        magnitude_value="50", magnitude_low="10", magnitude_high="20", magnitude_headline="50",
        magnitude_unit="percent of entry-level white-collar jobs; percent unemployment rate",
        specificity_tier="T1_quantified",
        horizon_stated_text="in the next one to five years", horizon_type="explicit_duration",
        horizon_start_year="2025", horizon_end_year="2030", horizon_operationalized="false",
        mechanism_specified="false",
        panic_valence="alarm", is_secondary_report="true", primary_source_status="secondary_only",
        tech=[("generative_ai", True), ("artificial_intelligence", False)],
        authors=[("auth_amodei", "sole", "industry_executive")],
    ),
]

DEFAULTS = {
    "geography": "", "geography_text": "", "occupation_code": "", "occupation_system": "",
    "industry_code": "", "industry_system": "", "magnitude_type": "", "estimate_type": "",
    "magnitude_value": "", "magnitude_low": "", "magnitude_high": "", "magnitude_headline": "",
    "magnitude_unit": "", "horizon_stated_text": "", "horizon_start_year": "",
    "horizon_end_year": "", "horizon_operationalized": "", "mechanism_text": "",
    "mechanism_type": "", "is_conditional": "", "is_secondary_report": "",
    "primary_source_status": "", "derived_from_prediction_id": "",
    "extraction_method": "llm_assisted", "llm_model": LLM_MODEL,
    "llm_prompt_version": PROMPT_V, "created_by": CREATED_BY, "created_date": CREATED_DATE,
    "verified_by": "", "verified_date": "", "record_status": "draft",
}


def write(name, header, rows):
    path = P / f"{name}.csv"
    with path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh, quoting=csv.QUOTE_MINIMAL, lineterminator="\n")
        w.writerow(header)
        w.writerows(rows)
    print(f"{name}.csv: {len(rows)} rows")


def main():
    # coders — add the AI coder alongside the two PIs
    write("coders", ["coder_id", "name", "role"], [
        ["jj", "Jonathan Jayes", "pi"],
        ["bs", "Ben Schneider", "pi"],
        ["cc", "Claude (claude-fable-5), AI assistant", "llm"],
    ])

    write("authors", ["author_id", "display_name", "author_type", "orcid_or_viaf", "notes"],
          [list(a) for a in AUTHORS])

    src_header = ["source_id", "title", "container_title", "pub_date", "source_type",
                  "venue_country", "language_original", "is_translation", "url",
                  "archive_url", "doi", "retrieval_track", "search_query_id",
                  "parent_source_id", "duplicates_of", "accessed_date",
                  "full_text_location", "notes"]
    wayback = json.loads((Path(__file__).parent / "wayback.json").read_text())
    src_rows = []
    for (sid, title, container, pub, stype, country, lang, istrans, url, arch, doi,
         track, notes) in SOURCES:
        full_text = ("data/raw/frey-2019-technology-trap.pdf"
                     if sid == "src_freyosborne2013" else "")
        arch = arch or wayback.get(sid, "")
        assert not url or arch, f"{sid}: url set but no archive snapshot"
        src_rows.append([sid, title, container, pub, stype, country, lang, istrans,
                         url, arch, doi, track, "", "", "", "2026-08-26", full_text, notes])
    write("sources", src_header, src_rows)

    pred_rows, pa_rows, pt_rows = [], [], []
    for p in PREDICTIONS:
        row = dict(DEFAULTS)
        techs = p.pop("tech")
        auths = p.pop("authors")
        row.update(p)
        pred_rows.append([row.get(f, "") for f in PRED_FIELDS])
        for aid, role, atype in auths:
            pa_rows.append([row["prediction_id"], aid, role, atype])
        primaries = sum(1 for _, is_p in techs if is_p)
        assert primaries == 1, f"{row['prediction_id']}: {primaries} primary techs"
        for tid, is_p in techs:
            pt_rows.append([row["prediction_id"], tid, str(is_p).lower()])

    write("predictions", PRED_FIELDS, pred_rows)
    write("prediction_authors",
          ["prediction_id", "author_id", "author_role", "author_type_at_prediction"], pa_rows)
    write("prediction_technologies", ["prediction_id", "tech_id", "is_primary"], pt_rows)


if __name__ == "__main__":
    main()
